name: flutter_task
description: Technical test task for a Flutter single-screen app.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  solid_lints: ^0.3.2

flutter:
  uses-material-design: true
